name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Windows binary
        run: go build -o goproxy.exe main.go

      - name: Publish Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: goproxy
          path: goproxy.exe

  release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: goproxy.exe
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release create
          "${{ github.ref_name }}"
          goproxy.exe
          --draft
          --title "${{ github.ref_name }}"
          --repo ${{ github.repository }}